name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Wait for CI checks
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'ci'
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 600
          intervalSeconds: 10

      - name: Wait for Playwright tests
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-playwright
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'playwright'
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 600
          intervalSeconds: 10

      - name: Auto-merge patch updates
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' &&
          steps.wait-for-ci.outputs.conclusion == 'success' &&
          steps.wait-for-playwright.outputs.conclusion == 'success'
        run: |
          echo "All checks passed, auto-merging patch update"
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add auto-merge comment
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' &&
          steps.wait-for-ci.outputs.conclusion == 'success' &&
          steps.wait-for-playwright.outputs.conclusion == 'success'
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "🤖 **Auto-merging patch update**

          This patch update has been automatically approved and merged because:
          ✅ CI tests passed
          ✅ Playwright tests passed
          ✅ This is a patch version update (\`${{ steps.metadata.outputs.update-type }}\`)

          **Dependencies updated:**
          ${{ steps.metadata.outputs.dependency-names }}

          If you need to make changes, you can always revert this merge."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log non-patch update
        if: steps.metadata.outputs.update-type != 'version-update:semver-patch'
        run: |
          echo "This is not a patch update (type: ${{ steps.metadata.outputs.update-type }}), skipping auto-merge"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
